/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.16
 * Generated at: 2019-03-18 05:05:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bbsupload2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/it/jsp-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bbs/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1552268969066L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>게시판 업로드데스</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<style>\r\n");
      out.write(" \r\n");
      out.write("\tbox {\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t\ttransition: border-color 0.2s ease-in-out;\r\n");
      out.write("\t    background: transparent;\r\n");
      out.write("\t    border-radius: 4px;\r\n");
      out.write("\t    border: solid 1px rgba(255, 255, 255, 0.3);\r\n");
      out.write("\t    color: inherit;\r\n");
      out.write("\t    text-decoration: none;\r\n");
      out.write("\t    \r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta {\r\n");
      out.write("\t\tcolor:white;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t\tborder-bottom-color:transparent;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("\t");

		String sessionID = null;
		if (session.getAttribute("sessionID") != null) {
			sessionID = (String) session.getAttribute("sessionID");
		}
	
      out.write("\r\n");
      out.write("\t<div class=\"wrapper style1\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<button class=\"button primary fit\"><a href=\"bbs.do\">게 시 판</a></button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<form method=\"post\" enctype=\"multipart/form-data\" action=\"bbsupload2.do\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t<td><h7>카테고리</h7></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"category\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 30%; padding: 12px 20px; font-size: 18px; margin: 10px 0px;  box-sizing: border-box; border-radius: 4px;\r\n");
      out.write("\t    \t\t\t\t\tborder: solid 1px rgba(255, 255, 255, 0.3);\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"math\">수학</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"enjoy\">여행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"pic\" selected>사진</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"java\">java</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"web\">웹프로그래밍</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"estate\">부동산</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"food\">음식</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"common\">상식</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t<td><h7 style=\"color:white\">제 목</h7></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\"><input name=\"title\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 90%; padding: 12px 20px; margin: 10px 0px; box-sizing: border-box; border-radius: 4px;\r\n");
      out.write("\t    border: solid 1px rgba(255, 255, 255, 0.3);\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t<td><h7 style=\"color:white\">내 용</h7></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\"><textarea name=\"content\" rows=\"20\" cols=\"80\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 90%; padding: 12px 20px; margin: 10px 0px; box-sizing: border-box; border-radius: 4px;\r\n");
      out.write("\t    border: solid 1px rgba(255, 255, 255, 0.3);\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr class=\"box\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tvar uf = \"\";\r\n");
      out.write("\t\t\t\t\t\t\tfunction file_add(size, ext) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar filecountTemp = parseInt(document\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.getElementById(\"file_cnt\").value);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar parents = document\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.getElementById(\"file_add_form\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar br = document.createElement(\"br\");\r\n");
      out.write("\t\t\t\t\t\t\t\tbr.setAttribute(\"id\", \"br\" + (filecountTemp + 1));\r\n");
      out.write("\t\t\t\t\t\t\t\tparents.appendChild(br);\r\n");
      out.write("\t\t\t\t\t\t\t\tif (filecountTemp == 30) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"파일업로드는 최대 30개까지 가능합니다\"); //< --- 이 부분 지우면 무한대로 추가됨.\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar obj = document.createElement(\"input\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tobj.setAttribute(\"type\", \"file\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\tobj.setAttribute(\"size\", size);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tobj.setAttribute(\"name\", \"bbs_file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ (filecountTemp + 1));\r\n");
      out.write("\t\t\t\t\t\t\t\t\tobj.setAttribute(\"id\", \"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t+ (filecountTemp + 1));\r\n");
      out.write("\t\t\t\t\t\t\t\t\tparents.appendChild(obj);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"file_cnt\").value = filecountTemp + 1;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tfunction file_delete() {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar filecountTemp = parseInt(document\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.getElementById(\"file_cnt\").value);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar parents = document\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.getElementById(\"file_add_form\");\r\n");
      out.write("\t\t\t\t\t\t\t\tvar obj = document.getElementById('file'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ filecountTemp);\r\n");
      out.write("\t\t\t\t\t\t\t\tvar br = document.getElementById('br'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ filecountTemp);\r\n");
      out.write("\t\t\t\t\t\t\t\tparents.removeChild(obj);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"file_cnt\").value = filecountTemp - 1;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"width: 50%;\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"row\" type=\"hidden\" id=\"file_cnt\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"file_cnt\" value=\"1\" > \r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:file_add(50, 'class=input_write');\"><b>첨부파일추가</b></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:file_delete();\"><b>첨부파일삭제</b></a>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td colspan=\"3\"></td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"button primary\">보내기\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href='bbs.do'>게시판</a>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<button class=\"button primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href='home.do'>처음으로</a>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"icons\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-twitter\"><span class=\"label\">Twitter</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-facebook\"><span class=\"label\">Facebook</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-linkedin\"><span class=\"label\">LinkedIn</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-instagram\"><span class=\"label\">Instagram</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-github\"><span class=\"label\">GitHub</span></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"icon alt fa-envelope\"><span class=\"label\">Email</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<ul class=\"copyright\">\r\n");
      out.write("\t\t\t\t\t\t<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</footer>\t\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
