/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-04-19 01:17:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class frmAddEmp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/resources/menu/head.jsp", Long.valueOf(1555549632000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>Simple Payroll v1</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"/resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- MetisMenu CSS -->\n");
      out.write("    <link href=\"/resources/vendor/metisMenu/metisMenu.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"/resources/dist/css/sb-admin-2.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Morris Charts CSS -->\n");
      out.write("    <link href=\"/resources/vendor/morrisjs/morris.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom Fonts -->\n");
      out.write("    <link href=\"/resources/vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div id=\"wrapper\">\n");
      out.write("\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Navigation -->\r\n");
      out.write("        <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"/index\">SSAGA Admin v1.0</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nav navbar-top-links navbar-right\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\r\n");
      out.write("                        <i class=\"fa fa-user fa-fw\"></i> <i class=\"fa fa-caret-down\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu dropdown-user\">\r\n");
      out.write("                        <li><a href=\"login\"><i class=\"fa fa-user fa-fw\"></i> Login</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"divider\"></li>\r\n");
      out.write("                        <li><a href=\"logout\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- /.dropdown-user -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- /.dropdown -->\r\n");
      out.write("            </ul>\r\n");
      out.write("            <!-- /.navbar-top-links -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/index\"><i class=\"fa fa-dashboard fa-fw\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope[\"comcode\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("인사정보관리</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-table fa-fw\"></i>기본정보관리</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"tblEmpList\">사원정보</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">수당정보</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">근태정보</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">휴가정보</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-edit fa-fw\"></i>급여작업</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">급상여대장생성</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">급여명세서생성</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">급여명세서발송</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-bar-chart-o fa-fw\"></i>보고서<span class=\"fa arrow\"></span></a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"tblEmpList\">근로계약서(개인)</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">급여명세서(개인)</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">급여(상여)대장</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">이체명세서</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-edit fa-fw\"></i>자료관리</a>\r\n");
      out.write("                            <ul class=\"nav nav-second-level\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">근로소득간이세액표생성</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\">4대보험세율설정</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <!-- /.nav-second-level -->\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.sidebar-collapse -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-static-side -->\r\n");
      out.write("        </nav>\r\n");
      out.write("\n");
      out.write("\t\n");
      out.write("         <div id=\"page-wrapper\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <h2 class=\"page-header\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope[\"comcode\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("사원정보 등록</h2>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.col-lg-12 -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.row -->\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <div class=\"panel panel-default\">\n");
      out.write("                        <div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t사원정보 등록\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"panel-body\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-lg-6\">\n");
      out.write("                                    <h3>기본정보등록</h3>\n");
      out.write("                                    <form role=\"form\" action=\"addEmployee\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>사원번호:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"EMPNO\" class=\"form-control\" placeholder=\"사원번호\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">사원번호는 입사일의 년,월,일에 두자리의 숫자를 사용하세요.(예:2019041601)!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>성명:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"EMPNAME\" class=\"form-control\" placeholder=\"성명\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>직급:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"TITLE\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"사원\">사원</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"대리\">대리</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"과장\">과장</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"차장\">차장</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"실장\">실장</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"소장\">소장</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"부장\">부장</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"이사\">이사</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"부사장\">부사장</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"대표이사\">대표이사</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>부서:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"DEPT\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"관리\">관리</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"외주\">외주</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"현대\">현대</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"기아\">기아</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"분당\">분당</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>근무지:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"LOCA\" class=\"form-control\" placeholder=\"근무지\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">근무지를 입력하세요!.</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>입사일자:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"INDATE\" type=\"date\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>비고:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"RMK\" type=\"text\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>월급:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"MSALARY\" type=\"number\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">연봉계약의 경우는 12분의 1을 입력하세요!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>기본시간:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"BTIME\" type=\"number\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">기본급에 해당하는 근무시간 (209시간)!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>고정연장시간:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"ETIME\" type=\"number\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">고정연장수당에 해당하는 근무시간!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>고정할증시간:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"ATIME\" type=\"number\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">할증수당에 해당하는 근무시간!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write(" \t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>식대:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"MEAL\" type=\"number\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">월급에 포함된 비과세항목으로서의 식대금액 (100,000)!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>자가운전:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"SELFCAR\" type=\"number\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">월급에 포함된 비과세항목으로서의 자가운전금액(200,000)!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>육아수당:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"BABY\" type=\"number\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">월급에 포함된 비과세항목으로서의 육아수당(100,000)!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>주소:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"ADDR1\" type=\"text\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>상세주소:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"ADDR2\" type=\"text\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>이메일:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"EMAIL\" type=\"email\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\">급여명세서 발송을 위한 이메일 주소!</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>집전화번호:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"HTEL\" type=\"text\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label>핸드폰:</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"MTEL\" type=\"text\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-primary\">등록</button>\n");
      out.write("                                        <button type=\"reset\" class=\"btn btn-default\">취소</button>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /.col-lg-6 (nested) -->                                \n");
      out.write("                                <div class=\"col-lg-6\">\n");
      out.write("                                    <h3>Excel파일을 이용한 사원등록</h3>\n");
      out.write("                                    <form role=\"form\" method=\"post\" action=\"addEmpFile\" enctype =\"multipart/form-data\">\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <label>파일을 선택하세요!</label>\n");
      out.write("                                            <p class=\"help-block\">반드시 제공되는 Excel Template을 사용하여야 합니다.!</p>\n");
      out.write("                                            <a href=\"fileDown.pay?fileName=TmplateEmployee\">Template 내려받기</a>\n");
      out.write("                                            <input name = \"fname\" type=\"file\" accept=\".xls,.xlsx\">\n");
      out.write("                                        </div>\n");
      out.write("                                           <button type=\"submit\" class=\"btn btn-primary\">파일로등록</button>\n");
      out.write("                                    </form>\n");
      out.write("                                    <h3>자료 정검 결과</h3>\n");
      out.write("                                    <form role=\"form\">\n");
      out.write("                                        <div class=\"form-group has-success\">\n");
      out.write("                                            <label class=\"control-label\" for=\"inputSuccess\">Input with success</label>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"inputSuccess\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group has-warning\">\n");
      out.write("                                            <label class=\"control-label\" for=\"inputWarning\">Input with warning</label>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"inputWarning\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group has-error\">\n");
      out.write("                                            <label class=\"control-label\" for=\"inputError\">Input with error</label>\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" id=\"inputError\">\n");
      out.write("                                        </div>\n");
      out.write("                                    </form>\n");
      out.write("                                </div>\n");
      out.write("                                <!-- /.col-lg-6 (nested) -->                                \n");
      out.write("                            </div>\n");
      out.write("                            <!-- /.row (nested) -->\n");
      out.write("                        </div>\n");
      out.write("                        <!-- /.panel-body -->\n");
      out.write("                    </div>\n");
      out.write("                    <!-- /.panel -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /.col-lg-12 -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.row -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /#page-wrapper -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /#wrapper -->\n");
      out.write("    \n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"/resources/vendor/jquery/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Metis Menu Plugin JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/metisMenu/metisMenu.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Morris Charts JavaScript -->\n");
      out.write("    <script src=\"/resources/vendor/raphael/raphael.min.js\"></script>\n");
      out.write("    <script src=\"/resources/vendor/morrisjs/morris.min.js\"></script>\n");
      out.write("    <script src=\"/resources/data/morris-data.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom Theme JavaScript -->\n");
      out.write("    <script src=\"/resources/dist/js/sb-admin-2.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
